title: Email Conversion Add-On
description: When provided a public Google Drive or Dropbox link, it will download the EML/MSG files in the link, convert them to PDF, and upload them to DocumentCloud. 
type: object
documents: []
properties:
 url:
    title: URL
    type: string
    format: uri
    description: A publicly accessible Google Drive or Dropbox folder or file. 
 attachments:
    title: Attempt Attachment Extraction
    type: boolean
required: 
  - url
  - attachments
